//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-b27-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.13 at 09:39:08 AM EDT 
//


package com.sun.identity.saml2.jaxb.metadataui;


/**
 * Java content class for Keywords element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Users/Doug/Work/OpenAM10/products/federation/library/xsd/saml2/sstc-saml-metadata-ui-v1.0.xsd line 57)
 * <p>
 * <pre>
 * &lt;element name="Keywords" type="{urn:oasis:names:tc:SAML:metadata:ui}KeywordsType"/>
 * </pre>
 * 
 */
public interface KeywordsElement
    extends javax.xml.bind.Element, com.sun.identity.saml2.jaxb.metadataui.KeywordsType
{


}
